## Video
profile=high-quality
vo=gpu-next
scale-antiring=0.6
dither-depth=8

## Decoding
# Intel VA-API hardware decoding
hwdec=auto-safe

## Debanding
deband=yes
deband-iterations=4
deband-threshold=64
deband-range=20
deband-grain=32

## Subtitles
blend-subtitles=video
slang=zh,en
alang=ja,en

## Judder reduction (23.976fps on 60Hz)
# 性能开销较高，按需开启
video-sync=display-resample
interpolation=yes
tscale=oversample

## Behavior
keep-open=yes
save-position-on-quit=yes

## Screenshots
screenshot-format=png
screenshot-dir="~/Pictures/mpv"
screenshot-template="%F-%p-%n"
screenshot-high-bit-depth=no

## OSC (disable built-in, use modern.lua)
osc=no

[Idle]
profile-cond=p["idle-active"]
profile-restore=copy-equal
title=' '
keepaspect=no
background=color
