# Hyprpaper 配置文件
# 文档: https://wiki.hyprland.org/Hypr-Ecosystem/hyprpaper/

# 预加载壁纸（必须先预加载才能使用）
preload = ~/Pictures/wallpaper/wallhaven-d88d53.png

# 为显示器设置壁纸（格式：wallpaper = 显示器名称,壁纸路径）
wallpaper = eDP-1,~/Pictures/wallpaper/wallhaven-d88d53.png

# 其他选项
splash = false    # 禁用启动 Logo
ipc = on          # 启用 IPC（可以动态切换壁纸）
