;;; ai-rc.el --- AI tooling integration  -*- lexical-binding: t; -*-

;;; Code:

(let* ((this-dir (file-name-directory (or load-file-name buffer-file-name)))
       (base-dir-candidate (expand-file-name "ai" (directory-file-name this-dir)))
       (base-dir (if (file-directory-p base-dir-candidate)
                     base-dir-candidate
                   (directory-file-name this-dir)))
       (core-dir (expand-file-name "core" base-dir))
       (ui-dir (expand-file-name "ui" base-dir))
       (ask-dir (expand-file-name "ask" base-dir))
       (complete-dir (expand-file-name "complete" base-dir))
       (complete-context-dir (expand-file-name "context" complete-dir))
       (complete-language-dir (expand-file-name "languages" complete-context-dir))
       (complete-lsp-dir (expand-file-name "lsp" complete-dir))
       (sessions-dir (expand-file-name "sessions" base-dir))
       (actions-dir (expand-file-name "actions" base-dir)))
  (dolist (dir (list base-dir core-dir ui-dir ask-dir complete-dir complete-context-dir complete-language-dir complete-lsp-dir sessions-dir actions-dir))
    (add-to-list 'load-path dir)))

(require 'ai-core-rc)
(require 'ai-action-state-rc)
(require 'ai-action-lifecycle-rc)
(require 'ai-action-request-rc)
(require 'ai-window-rc)
(require 'ai-ask-buffer-rc)
(require 'ai-ask-state-rc)
(require 'ai-ask-render-rc)
(require 'ai-ask-persist-rc)
(require 'ai-ask-command-rc)
(require 'ai-complete-state-rc)
(require 'ai-complete-observe-rc)
(require 'ai-complete-context-rc)
(require 'ai-complete-symbols-rc)
(require 'ai-complete-followup-rc)
(require 'ai-complete-cooldown-rc)
(require 'ai-complete-profile-rc)
(require 'ai-complete-schedule-rc)
(require 'ai-complete-candidates-rc)
(require 'ai-complete-lifecycle-rc)
(require 'ai-complete-trigger-rc)
(require 'ai-complete-lsp-rc)
(require 'ai-complete-tab-rc)
(require 'ai-action-inspect-rc)
(require 'ai-action-panel-rc)
(require 'ai-complete-inspect-rc)
(require 'ai-sessions-rc)
(require 'ai-action-rewrite-rc)
(require 'ai-action-complete-rc)

(provide 'ai-rc)
;;; ai-rc.el ends here
